### PR TITLE
Change `allowedValue` container to `@list`

### PR DESCRIPTION
**Pull request by amiller-ims**
`@set` is for unordered collections. Since `allowedValue` is an ordered collection, a more appropriate container type is `@list`.

- https://www.w3.org/TR/json-ld11/#lists
- https://www.imsglobal.org/spec/clr/v2p0/#resultdescription

### CODE REVIEW

**Comment by xaviaracil** [comment]
Does this change in the `@container` constitue a breaking change, which may lead to invalid signatures and errors? If so, we should create a new version of the context file

**Comment by amiller-ims** [comment]
> Does this change in the `@container` constitute a breaking change, which may lead to invalid signatures and errors? If so, we should create a new version of the context file

I suspect it does. Check out the n-quads that are generated in [this example ](https://json-ld.org/playground/#startTab=tab-expand&json-ld=%7B%0A%20%20%22%40context%22%3A%20%7B%0A%20%20%20%20%0A%20%20%20%20%22nick%22%3A%20%7B%0A%20%20%20%20%20%20%22%40id%22%3A%20%22http%3A%2F%2Fxmlns.com%2Ffoaf%2F0.1%2Fnick%22%2C%0A%20%20%20%20%20%20%22%40container%22%3A%20%22%40list%22%0A%20%20%20%20%7D%0A%20%20%7D%2C%0A%20%20%0A%20%20%22%40id%22%3A%20%22http%3A%2F%2Fexample.org%2Fpeople%23joebob%22%2C%0A%20%20%22nick%22%3A%20%5B%20%22joe%22%2C%20%22bob%22%2C%20%22jaybee%22%20%5D%0A%7D)when the `@container` is `@list` versus `@set`.

**Comment by xaviaracil** [comment]
Set new version of the `context.json` file, adjusting spec documents. Also described the change in the `ob_v3p0/errata/errata.md`.

**Comment by robcoyle913** [comment]
Do we need to add this to the next working group mtg?

**Comment by amiller-ims** [comment]
@ottonomy And `@vocab`, if not too controversial?

**Comment by xaviaracil** [comment]
@ottonomy did you have any feedback on your review about `@protected`?

**Comment by ottonomy** [comment]
@xaviaracil sorry it took me a while to actually commit it. See latest commit 718634d for the addition of `@protected` and two other changes

* `"@type": "xsd:string"` was removed where it appears. This is the default type, but in rare cases, processing systems handle an explicit declaration of this type differently from allowing the default. For VCs, it is considered more reliable to just allow the default to be applied.
* "id" and "type" aliases are redeclared in every context. This avoids a narrow type of attack where somebody might place a context that redeclares these terms in between the top layer and a class-specific layer of a credential, changing the values of these terms within the class implementation.

Overall, these changes promote the reliability of working with the source JSON data more directly more often, rather than needing to perform specific JSON-LD transforms prior to working with the data.

**Comment by ottonomy** [comment]
> @ottonomy And @vocab, if not too controversial?

I don't recommend using `@vocab` in the context. VC 2.0 will use `@vocab`, and when we update to allow use of that context, then we will have capabilities to use unmapped terms when desired. However, it is not a recommended practice to do so.

**Comment by amiller-ims** [comment]
> I don't recommend using `@vocab` in the context. VC 2.0 will use `@vocab`, and when we update to allow use of that context, then we will have capabilities to use unmapped terms when desired. However, it is not a recommended practice to do so. If you have any specific reasons to request the use of `@vocab`, we could chat about them.

No specific reason. I watched the conversation about `@vocab` in VC 2.0 and noted that they settled on including it. It might make experimental extensions easier. But I agree there is no pressing need to make that addition and since it is not a recommended practice, I withdraw my suggestion.

**Comment by ottonomy** [comment]
We should have identical aliases for `"id": "@id"` and `"type": "@type"` as is defined in the VC context.

* description appears in VCDM V2 context, but with the same mapping we use: https://github.com/w3c/vc-data-model/blob/main/contexts/credentials/v2#L29 and in a protected context specific to `VerifiableCredential` type.
* https://github.com/w3c/vc-data-model/blob/main/contexts/credentials/v2#L48 same with `name`

These shouldn't pose any conflicts with our context, because they're in a protected type-specific context.

**Pull request merged**
